@startuml
' a comment starts with single quote

note "\
Плагин предметной области - ППО\n\
Рассуждатель - бэкэнд Б\n\
Интерфейс студента - фронтэнд Ф\n\
Плагин стратегии - ПС\n\
УнФ - Универсальная форма" as n1

' state ППО

[*] --> Учитель

' 01 Учитель через интерфейс ППО определяет условия упражнения, и кто имеет к нему доступ.
Учитель --> ППО : 1.1.Настройка упражнения
ППО --> МодельВопроса : 1.2.Настройка упражнения

' 02 Ядро регистрирует упражнение в БД
МодельВопроса --> БД : 2.Упражнениe

' 03 Ученик начинает упражнение через Ф
Ученик --> Ф : 3.1.ID студента
Ф --> ВыборВопроса : 3.2.ID студента
ВыборВопроса --> ПС : 3.3.ID студента

' 04 ПС формирует задание на первый вопрос
ПС --> БД : 4.1.ID студента
БД --> ПС : 4.2.Статистика по студенту
ПС --> ВыборВопроса : 4.3.Параметры вопроса

' 05 ППО генерирует условие первого вопроса в двух формах: правил и человеко-понятной
ВыборВопроса --> ГенераторУсловий : 5.1.Параметры вопроса
ГенераторУсловий --> Ф : 5.2.Вопрос в УнФ

' 06 Ф выводит условие ученику
Ф -l-> Ученик : 6.Вопрос

' 07 ученик отвечает через Ф (первая интеракция)
Ученик --> Ф : 7.1.Ответ
Ф --> ОценкаОтвета : 7.2.Ответ в УнФ

' 08 используя Б, ядро оценивает ответ (правильно, нет, какие закономерности нарушены, где)
ОценкаОтвета --> Б : 8.1.Условие+Ответ
Б --> ОценкаОтвета : 8.2.Ошибки
ОценкаОтвета --> Ф : 8.3.Оценка(+Ошибки) в УнФ

' 09 Ф выводит ученику оценку, сообщение об ошибке (если была)
Ф --> Ученик : 9.Оценка(+Ошибки)

' 10 если ошибка, ученик запрашивает объяснение (если разрешено или автоматически если учитель задал) через Ф
Ученик --> Ф : 10.1.Запрос на объяснение
Ф --> ОценкаОтвета : (?) 10.2.Запрос на объяснение в УнФ
ОценкаОтвета --> ГенераторОбъяснений : (?) 10.3.Ошибки в УнФ

' 11 ППО формирует человекопонятное объяснение
ГенераторОбъяснений --> Конвертер_ЧПЯ: 11.1.Ошибка(-и) на ЧПЯ
Конвертер_ЧПЯ --> Ф : 11.2.Объяснение на ЧПЯ

' 12 Ф показывает человекопонятное объяснение
Ф --> Ученик: 12.Объяснение на ЧПЯ

' 13 ученик продолжает работу
' Ученик --> Ф : 13.Запрос на выдачу следующего вопроса
' Ф --> ВыборВопроса : 13.1.+ ID студента...
Ф --> [*] : 13.1+. ID студента...

' 14 ПС определяет требования к следующим интеракциям

' 15 ядро на основе требований от ПС, возможно запрашивая ППО будут ли интеракции проверяющие нужные закономерности в данном вопросе далее, принимает решение продолжить интеракции по этому вопросу или создать новый
ВыборВопроса --> ПС : 15.Запрос на закономерности, проверяемые вопросом


@enduml

' The following is ignored (if exist)
hello world ...